
services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ui_nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    env_file:
      - .env
    command: /bin/sh -c "envsubst '$$SERVER_NAME $$CERT_BASE_PATH' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - react-app
    restart: unless-stopped